name: build master
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12.19.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Ionic, Angular, Cordova
        run: npm install -g @ionic/cli @angular/cli cordova

      - name: Install and Test
        run: |
          npm install
          # ng lint
          # ng test -- --no-watch --no-progress --browsers=ChromeHeadless
          ng build --base-href=/residentialreporter-frontend/
          # ionic cordova build android --prod --release

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: www # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
